# student introduction system
print("***************student details******************")
name=input("enter your name:")
college=input("enter your college name:")
rollno=int(input("enter roll no.:"))
studentno=int(input("enter student no.:"))
add=input("enter your addres:")
age=int(input("enter your age:"))
print("***************type******************")
print(type(name))
print(type(college))
print(type(rollno))
print(type(studentno))
print(type(add))
print(type(age))
print("***************student deta******************")
print("name:",name)
print("college:",college)
print("roll no:",rollno)
print("student no:",studentno)
print("add:",add)
print("age:",age)
